backend:
  name: github
  repo: CUSings/website # Path to your GitHub repository
  # optional, defaults to master
  branch: main
media_folder: static/images
public_folder: /images/
collections:
  - name: content
    label: Content
    folder: content/
    fields:
      - { label: "Language", name: "language" }
