name: "Publish"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v27

    - run: nix develop --command hugo

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Build website from {{ github.sha }}"
        file_pattern: 'docs/'
